# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogInandOut():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logInandOut(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1821, 1040)
    self.driver.find_element(By.ID, "loginText").click()
    self.driver.find_element(By.ID, "loginButton").click()
    self.driver.find_element(By.ID, "loginEmail").click()
    self.driver.find_element(By.ID, "loginEmail").send_keys("758343984@qq.com")
    self.driver.find_element(By.ID, "loginPassword").send_keys("fengyunjia")
    self.driver.find_element(By.CSS_SELECTOR, ".center > .submit-btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".center > .submit-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".app-content-headerButton").click()
  
