# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignUp():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signUp(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1821, 1040)
    self.driver.find_element(By.ID, "loginText").click()
    self.driver.find_element(By.ID, "signupUsername").click()
    self.driver.find_element(By.ID, "signupUsername").send_keys("xiaozha")
    self.driver.find_element(By.ID, "signupUsername").click()
    self.driver.find_element(By.ID, "signupUsername").send_keys("xiaozhaz")
    self.driver.find_element(By.ID, "signupEmail").click()
    self.driver.find_element(By.ID, "signupEmail").send_keys("75@qq.com")
    self.driver.find_element(By.ID, "signupPassword").send_keys("fengyunjia")
    self.driver.find_element(By.CSS_SELECTOR, ".signup > .submit-btn").click()
  
